{% set name = "multicollections" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multicollections-{{ version }}.tar.gz
  sha256: aaeb7b2c1f4a54a508867935068569229a67f9be33fa93dbc182221e27b6976a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9,<0.10
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - multicollections
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gerlero/multicollections
  summary: Fully generic MultiDict class
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
