{% set name = "multicollections" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/multicollections-{{ version }}.tar.gz
  sha256: aa1b2fe0c465a1706199f9b3309ffedad0de8c02f6be45af8ccd93be91ab6412

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.11,<0.13
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - multicollections
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gerlero/multicollections
  summary: Fully generic MultiDict class
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
